### ISSUE TITLE
Do you have a quickstart example?

### ISSUE THREAD

**Issue by karakanb** [goccy/go-zetasql#2]
Hi there, this seems lovely but I couldn't manage to run it for a simple analyze of a `SELECT 1` query in a custom golang program, would you be able to add a quickstart program in the readme to show how it is being used? Thanks!

**Comment by goccy** [comment]
go-zetasql still only supports parser feature. The analyzer is currently under development. See [`parser_test.go`](https://github.com/goccy/go-zetasql/blob/8607e154d95576c8e69567c61fc647bb8bf1b99f/parser_test.go#L12-L53) for how to use parser

**Comment by karakanb** [comment]
thanks a lot, I'll start playing around with it. One of the problems I am having is to figure out what types would I get in the parsed result, and since there are many methods and types with similar name it seems to be a guessing game for now for me, would you have any recommendations about how to learn more about them?

**Comment by goccy** [comment]
You can either print the type with `%T` or look it up with [ast.Walk](https://pkg.go.dev/github.com/goccy/go-zetasql@v0.0.0-20220314080333-8607e154d955/ast#Walk) . Example is here https://github.com/goccy/go-zetasql/blob/8607e154d95576c8e69567c61fc647bb8bf1b99f/parser_test.go#L74-L77

**Comment by karakanb** [comment]
thanks a lot, I appreciate it, have a lovely day!
